const quotes = [
    { id: 1, author: "Abraham Lincoln", text: "Whatever you are, be a good one" },
    { id: 2, author: "Jean-Paul Sartre", text: "Hell is other people" },
    { id: 3, author: "Sir Francis Bacon", text: "Knowledge is power" },
    { id: 4, author: "Albert Einstein", text: "Life is like riding a bicycle. To keep your balance, you must keep moving" },
    { id: 5, author: "Walt Disney", text: "If you can dream it, you can do it" },
    { id: 6, author: "Vince Lombardi", text: "Winners never quit and quitters never win" },
    { id: 7, author: "Les Brown", text: "The harder the battle, the sweeter the victory" },
    { id: 8, author: "Theodore Roosevelt", text: "Speak softly and carry a big stick" },
    { id: 9, author: "Michael Jordan", text: "There are no shortcuts in life" },
    { id: 10, author: "Winston Churchill", text: "The price of greatness is responsibility" },
    { id: 11, author: "Hellen Keller", text: "Life is either a daring adventure or nothing at all" },
    { id: 12, author: "Confucius", text: "Life is really simple, but we insist on making it complicated" },
    { id: 13, author: "Thomas Edison", text: "I failed my way to success" },
    { id: 14, author: "Lady Gaga", text: "I'm not here to be perfect, I'm here to be real" },
    { id: 15, author: "Steve Jobs", text: "Your time is limited, don't waste it living someone else's life" },
    { id: 16, author: "Oprah Winfrey", text: "The best way to find out what you want in life is to try a lot of things" },
    { id: 17, author: "Lily Tomlin", text: "The road to success is always under construction" },
    { id: 18, author: "Stan Lee", text: "I'm not a self-made man. I've had a lot of help" },
    { id: 19, author: "Tony Robbins", text: "You've got to be in it to win it" },
    { id: 20, author: "Will Rogers", text: "Don't let yesterday take up too much of today" },
    { id: 21, author: "Nelson Mandela", text: "The greatest glory in living lies not in never falling, but in rising every time we fall" },
    { id: 22, author: "Oscar Wilde", text: "Be yourself; everyone else is already taken" },
    { id: 23, author: "Benjamin Franklin", text: "Well done is better than well said" },
    { id: 24, author: "Aristotle", text: "It is during our darkest moments that we must focus to see the light" },
    { id: 25, author: "Ralph Waldo Emerson", text: "Life is a succession of lessons which must be lived to be understood" },
    { id: 26, author: "Dalai Lama", text: "The purpose of our lives is to be happy" },
    { id: 27, author: "Mae West", text: "You only live once, but if you do it right, once is enough" },
    { id: 28, author: "John Wooden", text: "Do not let making a living prevent you from making a life" },
    { id: 29, author: "Hellen Keller", text: "Life is either a daring adventure or nothing" },
    { id: 30, author: "Ray Bradbury", text: "Life is trying things to see if they work" },
    { id: 31, author: "Mark Twain", text: "The Secret of getting ahead is getting started" },
    { id: 32, author: "Paulo Coelho", text: "Impossible is just an opinion" },
    { id: 33, author: "Ross Simmonds", text: "Greatness only comes before hustle in the dictionary." },
    { id: 34, author: "Aly Raisman", text: "The hard days are what make you stronger" },
    { id: 35, author: "Mahatma Gandhi", text: "In a gentle way, you can shake the world" },
    { id: 36, author: "Frank Ocean", text: "Work hard in silence, let your success be the noise" },
    { id: 37, author: "Tim Notke", text: "Hard work beats talent when talent doesn’t work hard" },
    { id: 38, author: "Mother Teresa", text: "The miracle is not that we do this work, but that we are happy to do it" },
    { id: 39, author: "Maya Angelou", text: "Nothing will work unless you do" },
    { id: 40, author: "Albert Einstein", text: "In the middle of every difficulty lies opportunity" },
    { id: 41, author: "Lilly Pulitzer", text: "Despite the forecast, live like it's spring" },
    { id: 42, author: "Margret Thatcher", text: "You may have to fight a battle more than once to win it" },
    { id: 43, author: "Jonathan Winters", text: "If your ship doesn’t come in, swim out to it!" },
    { id: 44, author: "Les Paul", text: "Don’t say you can’t until you prove you can’t" },
    { id: 45, author: "George Skolsky", text: "Kindness is one thing you can’t give away. It always comes back" },
    { id: 46, author: "David Endings", text: "No day in which you learn something is a complete loss" },
    { id: 47, author: "Peter Drucker", text: "The best way to predict the future is to create it" },
    { id: 48, author: "Tom Stoppard", text: "Every exit is an entry somewhere else" },
    { id: 49, author: "Bruce Barton", text: "If you can give your child only one gift, let it be enthusiasm" },
    { id: 50, author: "Queen Elizabeth", text: "Memories are everyone’s second chance at happiness" },
];


module.exports = quotes;